Repository seL4/l4v, pull requests merged in 2020-12, with the labels that each got.

#161 docs: factor out dependency specs
  README.md
  docs/setup.md
Labels: cleanup, docs

#154 rt lib+aspec+ainvs: replace sort_queue
  lib/HaskellLib_H.thy
  lib/Lib.thy
  proof/invariant-abstract/DetSchedDomainTime_AI.thy
  proof/invariant-abstract/DetSchedSchedule_AI.thy
  proof/invariant-abstract/EmptyFail_AI.thy
  proof/invariant-abstract/Finalise_AI.thy
  proof/invariant-abstract/IpcCancel_AI.thy
  proof/invariant-abstract/IpcDet_AI.thy
  proof/invariant-abstract/Ipc_AI.thy
  proof/invariant-abstract/RealTime_AI.thy
  proof/invariant-abstract/Tcb_AI.thy
  spec/abstract/IpcCancel_A.thy
  spec/abstract/Ipc_A.thy
Labels: MCS

#162 rt refine: remove BlockedOnReply from simple'
  proof/refine/ARM/Invariants_H.thy
  proof/refine/ARM/IpcCancel_R.thy
  proof/refine/ARM/Ipc_R.thy
Labels: MCS

#170 rt refine: make more use of reply projections
  lib/Lib.thy
  proof/refine/ARM/Finalise_R.thy
  proof/refine/ARM/Invariants_H.thy
  proof/refine/ARM/KHeap_R.thy
  proof/refine/ARM/Reply_R.thy
Labels: MCS

#173 rt refine: resurrect some crunches for updateReply
  proof/refine/ARM/Reply_R.thy
Labels: MCS

#177 arm_hyp: proof updates for seL4 commit 93ab2543d9d8
  proof/crefine/ARM_HYP/Arch_C.thy
  spec/abstract/ARM_HYP/VCPU_A.thy
  spec/haskell/src/SEL4/Machine/RegisterSet/ARM.lhs
  spec/haskell/src/SEL4/Object/VCPU/ARM.lhs
Labels: seL4-PR

#179 ainvs: reduce Finalise interface
  proof/invariant-abstract/ARM/ArchFinalise_AI.thy
  proof/invariant-abstract/ARM_HYP/ArchFinalise_AI.thy
  proof/invariant-abstract/Finalise_AI.thy
  proof/invariant-abstract/RISCV64/ArchFinalise_AI.thy
  proof/invariant-abstract/X64/ArchFinalise_AI.thy
Labels: enhancement
