Repository seL4/l4v, pull requests merged in 2020-11, with the labels that each got.

#116 rt refine: sorries in CNodeInv and Ipc
  proof/refine/ARM/CNodeInv_R.thy
  proof/refine/ARM/Ipc_R.thy
Labels: MCS

#142 rt refine: progress on finaliseCap sorries
  proof/refine/ARM/Finalise_R.thy
Labels: MCS

#138 rt refine: prove decode priority corres
  proof/refine/ARM/Tcb_R.thy
Labels: MCS

#131 lib: A tutorial and some 'modify' monad rules for Lib.EquivValid
  .github/workflows/proof.yml
  CONTRIBUTORS.md
  ROOTS
  lib/EVTutorial/EquivValidTutorial.thy
  lib/EVTutorial/ROOT
  lib/EVTutorial/document/root.bib
  lib/EVTutorial/document/root.tex
  lib/EquivValid.thy
  lib/tests.xml
Labels: enhancement

#144 rt: make valid_replies' easier to prove
  proof/invariant-abstract/DetSchedAux_AI.thy
  proof/invariant-abstract/IpcDet_AI.thy
  proof/refine/ARM/Finalise_R.thy
  proof/refine/ARM/Invariants_H.thy
  proof/refine/ARM/KHeap_R.thy
  spec/design/skel/KernelStateData_H.thy
  spec/haskell/src/SEL4/Model/StateData.lhs
  spec/haskell/src/SEL4/Object/ObjectType.lhs
Labels: MCS

#148 rt refine: add missing sc_replies_relation in state_relationD/E
  proof/refine/ARM/StateRelation.thy
Labels: MCS

#149 c-parser: improve asm support in modifies proofs
  tools/c-parser/CProof.thy
  tools/c-parser/modifies_proofs.ML
Labels: enhancement

#151 update publications links
  README.md
  proof/access-control/README.md
  proof/asmrefine/README.md
  proof/capDL-api/README.md
  proof/crefine/README.md
  proof/drefine/README.md
  proof/infoflow/README.md
  proof/invariant-abstract/README.md
  proof/refine/README.md
  proof/sep-capDL/README.md
  sys-init/README.md
  tools/README.md
  tools/asmrefine/README.md
Labels: enhancement

#153 lib: avoid internal index names
  lib/Lib.thy
Labels: bug

#152 update publications links
  README.md
  proof/access-control/README.md
  proof/asmrefine/README.md
  proof/capDL-api/README.md
  proof/crefine/README.md
  proof/drefine/README.md
  proof/infoflow/README.md
  proof/invariant-abstract/README.md
  proof/refine/README.md
  proof/sep-capDL/README.md
  sys-init/README.md
  tools/README.md
  tools/asmrefine/README.md
Labels: MCS

#150 autocorres: fix code inclusion in quickstart doc
  tools/autocorres/doc/quickstart/Chapter1_MinMax.thy
  tools/autocorres/doc/quickstart/Chapter2_HoareHeap.thy
  tools/autocorres/doc/quickstart/Chapter3_HoareHeap.thy
Labels: bug

#155 regression: increase CRefine timeout
  proof/tests.xml
Labels: proof performance

#159 crefine: proof update for seL4 7cc50c3039
  proof/crefine/ARM/Invoke_C.thy
  proof/crefine/ARM_HYP/Invoke_C.thy
  proof/crefine/RISCV64/Invoke_C.thy
  proof/crefine/X64/Invoke_C.thy
Labels: enhancement, seL4-PR
