Repository seL4/l4v, pull requests merged in 2020-08, with the labels that each got.

#33 lib/riscv refine: move lemma
  lib/Corres_UL.thy
  proof/refine/RISCV64/Untyped_R.thy
Labels: cleanup

#42 More ipc cancel sorries
  proof/refine/ARM/Finalise_R.thy
  proof/refine/ARM/IpcCancel_R.thy
  proof/refine/ARM/Schedule_R.thy
  proof/refine/ARM/TcbAcc_R.thy
Labels: MCS

#43 bump timeout
  proof/tests.xml
Labels: CI

#41 mcs: prove cancelBadgedSends_invs
  proof/refine/ARM/IpcCancel_R.thy
  proof/refine/ARM/TcbAcc_R.thy
Labels: MCS

#46 sc replies relation
  proof/refine/ARM/ADT_H.thy
  proof/refine/ARM/CSpace1_R.thy
  proof/refine/ARM/CSpace_R.thy
  proof/refine/ARM/Detype_R.thy
  proof/refine/ARM/Invariants_H.thy
  proof/refine/ARM/IpcCancel_R.thy
  proof/refine/ARM/KHeap_R.thy
  proof/refine/ARM/Retype_R.thy
  proof/refine/ARM/StateRelation.thy
Labels: MCS

#57 haskell: deal with existing "~/.stack"
  spec/haskell/Makefile
Labels: CI

#54 c-parser: avoid cleaning `umm_heap/ARM_HYP`
  tools/c-parser/standalone-parser/Makefile
Labels: cleanup

#35 riscv: rename sbadaddr -> stval
  proof/crefine/RISCV64/Machine_C.thy
  proof/crefine/RISCV64/VSpace_C.thy
  proof/invariant-abstract/RISCV64/ArchAcc_AI.thy
  proof/invariant-abstract/RISCV64/ArchEmptyFail_AI.thy
  proof/invariant-abstract/RISCV64/ArchSyscall_AI.thy
  proof/invariant-abstract/RISCV64/ArchVSpace_AI.thy
  proof/refine/RISCV64/Syscall_R.thy
  proof/refine/RISCV64/VSpace_R.thy
  spec/abstract/RISCV64/ArchVSpace_A.thy
  spec/design/skel/RISCV64/Hardware_H.thy
  spec/haskell/src/SEL4/Kernel/VSpace/RISCV64.hs
  spec/haskell/src/SEL4/Machine/Hardware/RISCV64.hs
  spec/machine/RISCV64/MachineOps.thy
Labels: enhancement, seL4-PR
