Repository seL4/l4v, pull requests merged in 2021-03, with the labels that each got.

#230 c-parser: use fresh names for temporaries
  tools/c-parser/program_analysis.ML
  tools/c-parser/syntax_transforms.ML
  tools/c-parser/testfiles/jiraver1389.c
  tools/c-parser/testfiles/jiraver1389.thy
Labels: BV, MCS, bug

#228 4 small sorries in Syscall_R.thy
  proof/refine/ARM/Syscall_R.thy
  proof/refine/ARM/TcbAcc_R.thy
Labels: MCS

#224 rt: make more use of reply projections
  proof/refine/ARM/Ipc_R.thy
  proof/refine/ARM/Reply_R.thy
Labels: MCS

#238 c-parser: rewrite functional-record-update fN defs
  tools/c-parser/FunctionalRecordUpdate.ML
Labels: enhancement, proof performance

#244 trivial: fix c-parser link
  tools/autocorres/README.md
Labels: cleanup

#245 rt: move schedContextDonate and related lemmas
  proof/refine/ARM/CNodeInv_R.thy
  proof/refine/ARM/Finalise_R.thy
  proof/refine/ARM/Invariants_H.thy
  proof/refine/ARM/IpcCancel_R.thy
  proof/refine/ARM/Ipc_R.thy
  proof/refine/ARM/Reply_R.thy
  proof/refine/ARM/Retype_R.thy
  proof/refine/ARM/SchedContext_R.thy
  proof/refine/ARM/Schedule_R.thy
  proof/refine/ARM/TcbAcc_R.thy
  proof/refine/ARM/Tcb_R.thy
  proof/refine/ARM/VSpace_R.thy
Labels: MCS

#254 riscv: use `uint8_t` for `register_t`
  lib/Word_Lib/Word_Lemmas_Internal.thy
  proof/crefine/RISCV64/StateRelation_C.thy
  proof/crefine/RISCV64/SyscallArgs_C.thy
  proof/crefine/RISCV64/TcbAcc_C.thy
  proof/crefine/RISCV64/Wellformed_C.thy
Labels: BV, RISCV64

#257 riscv: fix CLZ and CTZ for riscv32 builds
  proof/asmrefine/export/ARM/ArchSEL4SimplExport.thy
  proof/crefine/ARM/IpcCancel_C.thy
  proof/crefine/ARM_HYP/IpcCancel_C.thy
  proof/crefine/ARM_HYP/Syscall_C.thy
  proof/crefine/X64/IpcCancel_C.thy
  proof/crefine/X64/Syscall_C.thy
Labels: RISCV64, bug

#260 `bump` script for `verification-manifest`
  misc/bump/README.md
  misc/bump/bump-local-repos
  misc/bump/bump-ver-manifest
  misc/bump/ver-bump.py
Labels: CI
