Repository seL4/l4v, pull requests merged in 2021-07, with the labels that each got.

#297 valid_refills'
  proof/refine/ARM/Ipc_R.thy
  proof/refine/ARM/KHeap_R.thy
  proof/refine/ARM/SchedContextInv_R.thy
  proof/refine/ARM/Schedule_R.thy
  proof/refine/ARM/StateRelation.thy
Labels: MCS

#304 auto-deploy CParser docker container
  .github/workflows/trigger.yml
Labels: CI

#301 Support crunching lifted monadic functions
  lib/crunch-cmd.ML
  lib/test/Crunch_Test_NonDet.thy
  proof/invariant-abstract/CNodeInv_AI.thy
Labels: enhancement

#306 rt: support crunching lifted monadic functions
  lib/Crunch_Test_NonDet.thy
  lib/crunch-cmd.ML
Labels: MCS

#307 rt: replace call to `smt`
  proof/refine/ARM/StateRelation.thy
Labels: MCS

#302 rename opt_map_left_Some to opt_map_red
  lib/Monad_WP/OptionMonad.thy
  proof/invariant-abstract/DetSchedSchedule_AI.thy
  proof/refine/ARM/Invariants_H.thy
  proof/refine/ARM/IpcCancel_R.thy
  proof/refine/ARM/Ipc_R.thy
  proof/refine/ARM/KHeap_R.thy
  proof/refine/ARM/Reply_R.thy
  proof/refine/ARM/SchedContextInv_R.thy
  proof/refine/ARM/SchedContext_R.thy
  proof/refine/ARM/Schedule_R.thy
  proof/refine/ARM/StateRelation.thy
Labels: MCS

#309 run rt proofs on AWS
  .github/workflows/proof.yml
Labels: CI, MCS

#310 More readable proof logs
  misc/regression/run_tests.py
  run_tests
Labels: CI

#311 cherry-picking nicer log commits
  misc/regression/run_tests.py
  run_tests
Labels: CI, MCS

#317 github: scheduled external + weekly clean proofs
  .github/workflows/external.yml
  .github/workflows/weekly-clean.yml
Labels: CI
