Repository seL4/l4v, pull requests merged in 2021-11, with the labels that each got.

#388 Document variable name conventions
  docs/conventions.md
Labels: docs

#383 `refillNew_invs'` and `refillUpdate_invs'`
  proof/refine/ARM/Invariants_H.thy
  proof/refine/ARM/Retype_R.thy
  proof/refine/ARM/SchedContextInv_R.thy
  proof/refine/ARM/SchedContext_R.thy
Labels: MCS

#392 Notify if crunch generates side-conditions
  lib/crunch-cmd.ML
Labels: enhancement

#394 `performInv_invs`
  proof/refine/ARM/SchedContext_R.thy
  proof/refine/ARM/Syscall_R.thy
  proof/refine/ARM/TcbAcc_R.thy
Labels: MCS
