Repository seL4/l4v, pull requests merged in 2021-01, with the labels that each got.

#184 rt haskell: revert accidental edit
  spec/haskell/src/SEL4/Object/CNode.lhs
Labels: MCS

#192 readme: use -R instead of -l
  README.md
Labels: docs

#188 enable theory lint action
  .github/workflows/pr.yml
Labels: CI

#193 cherry-pick thylint action from master branch
  .github/workflows/pr.yml
Labels: CI, MCS

#190 rt: more consistent thread_state discriminators
  proof/invariant-abstract/ARM/ArchFinalise_AI.thy
  proof/invariant-abstract/DetSchedInvs_AI.thy
  proof/invariant-abstract/DetSchedSchedule_AI.thy
  proof/invariant-abstract/Finalise_AI.thy
  proof/invariant-abstract/Interrupt_AI.thy
  proof/invariant-abstract/Invariants_AI.thy
  proof/invariant-abstract/IpcCancel_AI.thy
  proof/invariant-abstract/IpcDet_AI.thy
  proof/invariant-abstract/Ipc_AI.thy
  proof/invariant-abstract/RISCV64/ArchFinalise_AI.thy
  proof/invariant-abstract/Syscall_AI.thy
  proof/invariant-abstract/TcbAcc_AI.thy
  proof/refine/ARM/IpcCancel_R.thy
  spec/abstract/Structures_A.thy
Labels: MCS

#196 rt: disable sorry words in thylint action
  .github/workflows/pr.yml
Labels: MCS

#198 thylint: ignore annotation errors
  .github/workflows/pr.yml
Labels: CI, enhancement

#197 Small decode sorries
  proof/refine/ARM/Tcb_R.thy
Labels: MCS

#195 rt: update unbindFromSC
  proof/refine/ARM/Finalise_R.thy
  spec/haskell/src/SEL4/Object/SchedContext.lhs
Labels: MCS

#200 Simple page table duplicate sorries
  proof/refine/ARM/PageTableDuplicates.thy
Labels: MCS

#203 rt: use updateReply everywhere
  proof/refine/ARM/Finalise_R.thy
  spec/haskell/src/SEL4/Object/Reply.lhs
  spec/haskell/src/SEL4/Object/SchedContext.lhs
Labels: MCS

#145 rt refine+haskell: prove tc_corres_caps and tc_corres_sched
  lib/Corres_UL.thy
  proof/invariant-abstract/Ipc_AI.thy
  proof/refine/ARM/Detype_R.thy
  proof/refine/ARM/KHeap_R.thy
  proof/refine/ARM/PageTableDuplicates.thy
  proof/refine/ARM/Retype_R.thy
  proof/refine/ARM/Syscall_R.thy
  proof/refine/ARM/TcbAcc_R.thy
  proof/refine/ARM/Tcb_R.thy
  spec/haskell/src/SEL4/API/Invocation.lhs
  spec/haskell/src/SEL4/Object/SchedContext.lhs
  spec/haskell/src/SEL4/Object/TCB.lhs
Labels: MCS

#209 rt: set refills to empty in finalise_cap
  proof/invariant-abstract/ARM/ArchFinalise_AI.thy
  proof/invariant-abstract/ARM/ArchVSpaceEntries_AI.thy
  proof/invariant-abstract/DetSchedDomainTime_AI.thy
  proof/invariant-abstract/DetSchedSchedule_AI.thy
  proof/invariant-abstract/Finalise_AI.thy
  proof/invariant-abstract/RISCV64/ArchFinalise_AI.thy
  spec/abstract/CSpace_A.thy
  spec/abstract/SchedContext_A.thy
Labels: MCS
