Repository seL4/l4v, pull requests merged in 2021-05, with the labels that each got.

#283 setup docs: markdown lint and slight tweaks
  docs/setup.md
Labels: docs

#282 PageTableDuplicates (2 sorries)
  proof/refine/ARM/Ipc_R.thy
  proof/refine/ARM/PageTableDuplicates.thy
Labels: MCS

#231 arm crefine: fix `decodeARMMMUInvocation` branch hint
  proof/crefine/ARM/Arch_C.thy
  proof/crefine/ARM_HYP/Arch_C.thy
Labels: BV, MCS
