Repository seL4/l4v, pull requests merged in 2022-01, with the labels that each got.

#418 github: run AWS proofs only on most recent push
  .github/workflows/proof-deploy.yml
  .github/workflows/proof.yml
Labels: CI

#422 Page table abstraction for experimental-timeprot
  proof/infoflow/timeprotection/MemSysExample_Generic32Bit_A.thy
  proof/infoflow/timeprotection/TimeProtection.thy
Labels: enhancement

#426 Move to AInvs
  proof/invariant-abstract/ARM/ArchKHeap_AI.thy
  proof/invariant-abstract/ARM/ArchTcbAcc_AI.thy
  proof/invariant-abstract/DetSchedInvs_AI.thy
  proof/invariant-abstract/DetSchedSchedule_AI.thy
  proof/invariant-abstract/Invariants_AI.thy
  proof/invariant-abstract/IpcCancel_AI.thy
  proof/invariant-abstract/IpcDet_AI.thy
  proof/invariant-abstract/KHeap_AI.thy
  proof/invariant-abstract/RISCV64/ArchKHeap_AI.thy
  proof/invariant-abstract/RISCV64/ArchTcbAcc_AI.thy
  proof/invariant-abstract/Tcb_AI.thy
  proof/refine/ARM/Finalise_R.thy
  proof/refine/ARM/IpcCancel_R.thy
  proof/refine/ARM/Ipc_R.thy
  proof/refine/ARM/Refine.thy
  proof/refine/ARM/Syscall_R.thy
  proof/refine/ARM/TcbAcc_R.thy
  proof/refine/ARM/Tcb_R.thy
  spec/abstract/IpcCancel_A.thy
  spec/haskell/src/SEL4/Object/Endpoint.lhs
Labels: MCS
