Repository seL4/l4v, pull requests merged in 2022-07, with the labels that each got.

#498 ci: temporarily remove mcs-export from proof-deploy
  .github/workflows/proof-deploy.yml
Labels: CI

#500 Sorry till end of `TcbQueue_C.thy`
  proof/crefine/RISCV64/CSpace_C.thy
  proof/crefine/RISCV64/PSpace_C.thy
  proof/crefine/RISCV64/SR_lemmas_C.thy
  proof/crefine/RISCV64/TcbAcc_C.thy
  proof/crefine/RISCV64/TcbQueue_C.thy
Labels: MCS

#502 riscv haskell+proofs: fix PageTablePTE encoding
  proof/crefine/RISCV64/Arch_C.thy
  proof/crefine/RISCV64/StateRelation_C.thy
  proof/crefine/RISCV64/VSpace_C.thy
  proof/infoflow/refine/RISCV64/Example_Valid_StateH.thy
  proof/refine/RISCV64/ADT_H.thy
  proof/refine/RISCV64/StateRelation.thy
  spec/haskell/src/SEL4/Kernel/VSpace/RISCV64.hs
  spec/haskell/src/SEL4/Machine/Hardware/RISCV64.hs
Labels: seL4-PR

#504 Sorry until the end of `Retype_C.thy`
  proof/crefine/RISCV64/Retype_C.thy
  proof/crefine/RISCV64/StoreWord_C.thy
  proof/crefine/RISCV64/VSpace_C.thy
Labels: MCS

#509 Sorry `Finalise_C.thy`
  proof/crefine/RISCV64/Finalise_C.thy
  proof/crefine/RISCV64/IpcCancel_C.thy
Labels: MCS
