Repository seL4/l4v, pull requests merged in 2023-12, with the labels that each got.

#698 arm-hyp crefine: update length to word_t for VCPU functions
  proof/crefine/ARM_HYP/Arch_C.thy
Labels: seL4-PR

#697 Further improvements to ccorres_While
  lib/clib/CCorresLemmas.thy
Labels: enhancement

#700 github: docs for platform branch rebase workflow
  .github/workflows/proof-deploy.yml
Labels: CI

#702 github: add num_domains key to artifact upload
  .github/workflows/proof-deploy.yml
  .github/workflows/weekly-clean.yml
Labels: CI
