Repository seL4/l4v, pull requests merged in 2024-04, with the labels that each got.

#744 aarch64 crefine: update to match other arches
  proof/crefine/AARCH64/VSpace_C.thy
Labels: cleanup

#745 docs: add cross compilers to Linux dependencies
  docs/setup.md
Labels: docs

#749 Improve WP_README's description of rule ordering
  lib/Monads/wp/WP_README.thy
Labels: docs

#750 lib: add wp_comb section to crunch
  lib/Crunch.ML
  lib/crunch-cmd.ML
Labels: proof tools
