Repository seL4/l4v, pull requests merged in 2024-07, with the labels that each got.

#755 docs: document platform branch procedure
  docs/platform-branches.md
Labels: docs

#771 docs: update arch-split
  docs/arch-split.md
Labels: docs

#774 make proofs generic in `config_ARM_PA_SIZE_BITS_40`
  proof/crefine/AARCH64/CSpace_C.thy
  proof/crefine/AARCH64/Finalise_C.thy
  proof/crefine/AARCH64/Invoke_C.thy
  proof/crefine/AARCH64/Retype_C.thy
  proof/crefine/AARCH64/SR_lemmas_C.thy
  proof/invariant-abstract/AARCH64/ArchInvariants_AI.thy
  proof/refine/AARCH64/ArchAcc_R.thy
Labels: Aarch64, proof engineering

#775 github: add tests for exynos5, zynqmp, bcm2711
  .github/workflows/proof-deploy.yml
Labels: CI

#778 github: upgrade permissions for annotation action
  .github/workflows/pr.yml
Labels: CI

#779 github: fix platform build matrix
  .github/workflows/proof-deploy.yml
Labels: CI

#780 github: more authorised token for annotations
  .github/workflows/lint.yml
  .github/workflows/pr.yml
Labels: CI

#789 Several sorries in `IpcCancel_C`
  proof/crefine/RISCV64/Arch_C.thy
  proof/crefine/RISCV64/Finalise_C.thy
  proof/crefine/RISCV64/Interrupt_C.thy
  proof/crefine/RISCV64/Invoke_C.thy
  proof/crefine/RISCV64/IpcCancel_C.thy
  proof/crefine/RISCV64/Ipc_C.thy
  proof/crefine/RISCV64/Schedule_C.thy
  proof/crefine/RISCV64/Tcb_C.thy
  proof/refine/RISCV64/InterruptAcc_R.thy
  proof/refine/RISCV64/IpcCancel_R.thy
  proof/refine/RISCV64/Ipc_R.thy
  proof/refine/RISCV64/Reply_R.thy
  proof/refine/RISCV64/Schedule_R.thy
  proof/refine/RISCV64/TcbAcc_R.thy
  proof/refine/RISCV64/Tcb_R.thy
  spec/design/skel/KernelStateData_H.thy
  spec/haskell/src/SEL4/Kernel/Thread.lhs
  spec/haskell/src/SEL4/Model/StateData.lhs
  spec/haskell/src/SEL4/Object/Notification.lhs
Labels: MCS

#798 github: remove rt branch test; switch to mcs-devel.xml
  .github/workflows/proof.yml
Labels: CI, MCS

#799 github: add mcs manifest deployment
  .github/workflows/proof-deploy.yml
Labels: CI

#796 Prove `awaken_ccorres`
  proof/crefine/RISCV64/Finalise_C.thy
  proof/crefine/RISCV64/Ipc_C.thy
  proof/crefine/RISCV64/SR_lemmas_C.thy
  proof/crefine/RISCV64/Schedule_C.thy
  proof/crefine/RISCV64/Tcb_C.thy
  proof/invariant-abstract/DetSchedSchedule_AI.thy
  proof/invariant-abstract/Syscall_AI.thy
  proof/refine/RISCV64/EmptyFail_H.thy
  proof/refine/RISCV64/Ipc_R.thy
  proof/refine/RISCV64/KHeap_R.thy
  proof/refine/RISCV64/Schedule_R.thy
  proof/refine/RISCV64/TcbAcc_R.thy
  spec/abstract/Schedule_A.thy
  spec/design/skel/KernelStateData_H.thy
  spec/haskell/src/SEL4/Model/StateData.lhs
  spec/haskell/src/SEL4/Object/SchedContext.lhs
  spec/haskell/src/SEL4/Object/TCB.lhs
Labels: MCS

#802 README: adjust CI proof badges
  README.md
Labels: CI, docs

#803 github: factor out platform rebase into own workflow
  .github/workflows/proof-deploy.yml
  .github/workflows/rebase.yml
Labels: CI
