Repository seL4/l4v, pull requests merged in 2024-12, with the labels that each got.

#832 lib/monads: use `experiment` for demo lemmas
  lib/Monads/wp/Datatype_Schematic.thy
  lib/Monads/wp/WPBang.thy
  lib/Monads/wp/WPFix.thy
  lib/Monads/wp/WP_Pre.thy
Labels: cleanup

#825 x64 crefine: proof update after change to C
  proof/crefine/X64/Arch_C.thy
Labels: seL4-PR

#835 github: fix concurrency group syntax
  .github/workflows/proof-deploy.yml
  .github/workflows/proof.yml
Labels: CI

#834 Style guide: _tac instantiations and attributes
  docs/Style.thy
Labels: docs
